package io.github.lucciani.msavaliadorcredito.application.exception;

public class DadosClienteNotFoundException extends Exception {
    public DadosClienteNotFoundException() {
        super("Dados do cliente n√£o encontrado par ao CPF informado.");
    }
}
